{"name": "test_02", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2 == 1", "trace": "def test_02():\n        print(\"测试11\")\n>       assert 2==1\nE       assert 2 == 1\n\ntest_01.py:4: AssertionError"}, "start": 1679971311101, "stop": 1679971311102, "uuid": "39d19845-c3c9-4d39-90e7-ed60aba6c51c", "historyId": "7632a118acfd9dca11133202e509eb6e", "testCaseId": "9b275c03c7f4ddfd82824b378e099007", "fullName": "test_01#test_02", "labels": [{"name": "suite", "value": "test_01"}, {"name": "host", "value": "DESKTOP-198SK6H"}, {"name": "thread", "value": "11272-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_01"}]}